name: MacOs Workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-10.15

    steps:
       - name: Checkout
         uses: actions/checkout@main
       - name: ffmpeg
       - uses: FedericoCarboni/setup-ffmpeg@v1
       - name: nodejs
       - uses: actions/setup-node@v3
         with:
           node-version: '14'
           check-latest: true
       - run: npm install
       - name essentials 
       - run: brew install git
       - run: brew update
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repo
         continue-on-error: false
         run: |
           git clone https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@${{ secrets.CREDS }} SedLoif
       - name: Running Ultroid
         timeout-minutes: 350
         continue-on-error: true
         run: |
           git clone https://github.com/TeamUltroid/Ultroid
           cp SedLoif/.env Ultroid/.env
           cd Ultroid
           pip3 install --no-cache-dir --ignore-installed --force-reinstall -U -r req*
           pip3 install --no-cache-dir --ignore-installed --force-reinstall -U -r res*/sta*/opt*.txt
           bash startup
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
