#Docker Work na BSDK

name: Ultroid Workflow

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-12

    steps:
       - name: Checkout
         uses: actions/checkout@main
       - name: Nodjs
         uses: actions/setup-node@v3
         with:
           node-version: 16
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@${{ secrets.CREDS }} SedLoif
       - name: Running Ultroid
         timeout-minutes: 350
         continue-on-error: true
         run: |
           sudo sh action.sh
           cp SedLoif/.env /root/Ultroid
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
